name: test

on:
  push:
    branches:
      - 'sprint-*'

jobs:
  sprint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'dev',
              head: context.ref,
            });
            
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'dev',
              head: context.ref,
            });
            if (pulls.length > 0) {
              return;
            }

            const regex = /sprint-(\d+)/;
            const matches = text.match(regex);

            if (!matches) {
              return;
            } 

            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Sprint ${matches[1]} to dev`,
              base: 'dev',
              head: context.ref,
              body: 'Automatically created pull request',
            });